### ISSUE TITLE
发行版release安装后闪退

### ISSUE THREAD

**Issue by WANGNlMA** [ligun123/xfvoice#1]

**Comment by al4fun** [comment]
你遇到的可能是这个问题：https://blog.csdn.net/al4fun/article/details/95855401

**Comment by WANGNlMA** [comment]
谢谢，已经解决了

**Comment by ixzk** [comment]
@WANGNlMA  请教如何解决的，我这里还是会闪退

**Comment by EverythingIsNothing** [comment]
在android的app目录下的build.gradle中取消代码混淆（minifyEnable和shrinkResources都设置为false），我这里就不闪退了
`buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
            // proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }`
